import { FormElement } from "./types";

// export const configurationOfElement: FormElement[] = [
//   {
//     id: 1,
//     name: "Short Text",
//     type: "text",
//     label: "Short Text",
//     placeholder: "Enter text...",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 2,
//     name: "Long Text",
//     type: "textarea",
//     label: "Long Text",
//     placeholder: "Enter detailed text...",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 3,
//     name: "Email",
//     type: "email",
//     label: "Email",
//     placeholder: "Enter your email...",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 4,
//     name: "Password",
//     type: "password",
//     label: "Password",
//     placeholder: "Enter your password...",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 5,
//     name: "Number",
//     type: "number",
//     label: "Number",
//     placeholder: "Enter a number...",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 6,
//     name: "Phone",
//     type: "tel",
//     label: "Phone Number",
//     placeholder: "Enter your phone number...",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 7,
//     name: "URL",
//     type: "url",
//     label: "Website",
//     placeholder: "https://example.com",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 8,
//     name: "Date",
//     type: "date",
//     label: "Select Date",
//     placeholder: "",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 9,
//     name: "Time",
//     type: "time",
//     label: "Select Time",
//     placeholder: "",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 10,
//     name: "Date & Time",
//     type: "datetime-local",
//     label: "Select Date & Time",
//     placeholder: "",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 11,
//     name: "Checkbox",
//     type: "checkbox",
//     label: "Checkbox",
//     placeholder: "",
//     required: false,
//     disabled: false,
//     defaultValue: false,
//   },
//   {
//     id: 12,
//     name: "Radio Group",
//     type: "radio",
//     label: "Choose an Option",
//     placeholder: "",
//     required: false,
//     disabled: false,
//     options: [
//       {
//         label: "Option 1",
//         value: "option1",
//       },
//       {
//         label: "Option 2",
//         value: "option2",
//       },
//     ],
//   },
//   {
//     id: 13,
//     name: "Select",
//     type: "select",
//     label: "Select an Option",
//     placeholder: "Choose an option",
//     required: false,
//     disabled: false,
//     options: [
//       {
//         label: "Option 1",
//         value: "option1",
//       },
//       {
//         label: "Option 2",
//         value: "option2",
//       },
//     ],
//   },
//   {
//     id: 14,
//     name: "Multi Select",
//     type: "multiselect",
//     label: "Select Multiple Options",
//     placeholder: "Choose one or more options",
//     required: false,
//     disabled: false,
//     options: [
//       {
//         label: "Option 1",
//         value: "option1",
//       },
//       {
//         label: "Option 2",
//         value: "option2",
//       },
//     ],
//   },
//   {
//     id: 15,
//     name: "File Upload",
//     type: "file",
//     label: "Upload File",
//     placeholder: "",
//     required: false,
//     disabled: false,
//   },
//   {
//     id: 16,
//     name: "Range Slider",
//     type: "range",
//     label: "Range",
//     placeholder: "",
//     required: false,
//     disabled: false,
//     min: 0,
//     max: 100,
//     step: 1,
//     defaultValue: 50,
//   },
//   {
//     id: 17,
//     name: "Color Picker",
//     type: "color",
//     label: "Pick a Color",
//     placeholder: "",
//     required: false,
//     disabled: false,
//     defaultValue: "#3b82f6",
//   },
// ];

export const configurationOfElement: FormElement[] = [
  {
    id: 1,
    name: "Short Text",
    type: "text",
    label: "Short Text",
    placeholder: "Enter text...",
    required: false,
    disabled: false,
  },
  {
    id: 2,
    name: "Long Text",
    type: "textarea",
    label: "Long Text",
    placeholder: "Enter detailed text...",
    required: false,
    disabled: false,
  },
  {
    id: 3,
    name: "Email",
    type: "email",
    label: "Email",
    placeholder: "Enter your email...",
    required: false,
    disabled: false,
  },
  {
    id: 4,
    name: "Number",
    type: "number",
    label: "Number",
    placeholder: "Enter a number...",
    required: false,
    disabled: false,
  },
  {
    id: 5,
    name: "Date",
    type: "date",
    label: "Select Date",
    placeholder: "",
    required: false,
    disabled: false,
  },
  {
    id: 6,
    name: "Checkbox",
    type: "checkbox",
    label: "Checkbox",
    placeholder: "",
    required: false,
    disabled: false,
    defaultValue: false,
  },
  {
    id: 7,
    name: "Select",
    type: "select",
    label: "Select an Option",
    placeholder: "Choose an option",
    required: false,
    disabled: false,
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
  },
  {
    id: 8,
    name: "Rating",
    type: "rating",
    label: "Rating",
    placeholder: "",
    required: false,
    disabled: false,
    min: 1,
    max: 5,
    defaultValue: 0,
  },
];
